### ISSUE TITLE
memory quota exceeding on renaming files

### ISSUE THREAD

**Issue by IamJithendra** [eyaadh/megadlbot_oss#47]
When renaming files on Telegram using memory downloads for rename as settings it is facing memory quota exceeding problem on Heroku

**Comment by eyaadh** [comment]
This is not an issue with the code no the repo. It is because the host machine (even if it's heroku or otherwise) does not have enough memory to download and serve the BytesIO stream for the file from memory, change the settings to write to disk instead of using memory - if you want to run around the issue on a machine that has a smaller memory.
